name: Flutter CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  FLUTTER_VERSION: "3.32.0"
  JAVA_VERSION: "11"

jobs:
  # Job 1: Code Analysis and Tests
  analyze_and_test:
    name: Analyze & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Generate code (if needed)
        run: flutter pub run build_runner build --delete-conflicting-outputs
        continue-on-error: true

      - name: Format check
        run: dart format --line-length=100 lib/ test/ --set-exit-if-changed
        continue-on-error: false

      - name: Analyze
        run: flutter analyze
        continue-on-error: false

      - name: Run unit and widget tests
        run: flutter test --coverage --no-test-assets

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: flutter
          name: flutter-coverage
        continue-on-error: true

  # Job 2: Build Android APK
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: analyze_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Build APK (release)
        run: |
          flutter build apk \
            --release \
            --obfuscate \
            --split-debug-info=build/symbols \
            --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7

      - name: Upload symbols
        uses: actions/upload-artifact@v3
        with:
          name: android-symbols
          path: build/symbols/
          retention-days: 30

  # Job 3: Build Android App Bundle
  build_app_bundle:
    name: Build Android App Bundle
    runs-on: ubuntu-latest
    needs: analyze_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build App Bundle
        run: |
          flutter build appbundle \
            --release \
            --obfuscate \
            --split-debug-info=build/symbols

      - name: Upload App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: android-bundle
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7

  # Job 4: Build iOS App
  build_ios:
    name: Build iOS App
    runs-on: macos-latest
    needs: analyze_and_test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS App
        run: |
          flutter build ios \
            --release \
            --obfuscate \
            --split-debug-info=build/symbols \
            --no-codesign

      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ios-app
          path: build/ios/iphoneos/Runner.app
          retention-days: 7

  # Job 5: Security Scan
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: analyze_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
        continue-on-error: true

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

  # Job 6: Deploy to Firebase App Distribution (optional)
  deploy_firebase:
    name: Deploy to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [analyze_and_test, build_android, build_app_bundle]
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build debug APK for testing
        run: flutter build apk --debug

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: firebase-key.json
          file: build/app/outputs/flutter-apk/app-debug.apk
          releaseNotes: "Build from commit ${{ github.sha }}"
          testers: "testers-group@example.com"
        env:
          FIREBASE_CREDENTIAL: ${{ secrets.FIREBASE_CREDENTIAL }}
        continue-on-error: true

  # Job 7: Notify on Slack (optional)
  notify:
    name: Notify Slack
    runs-on: ubuntu-latest
    needs: [analyze_and_test, build_android]
    if: always()

    steps:
      - name: Determine status
        id: status
        run: |
          if [[ "${{ needs.analyze_and_test.result }}" == "success" &&
                "${{ needs.build_android.result }}" == "success" ]]; then
            echo "status=✅ Success" >> $GITHUB_OUTPUT
          else
            echo "status=❌ Failed" >> $GITHUB_OUTPUT
          fi

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: 'Flutter Build ${{ steps.status.outputs.status }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
          fields: repo,message,commit,author
        if: always()
