import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';
import 'package:dio/dio.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

// Generated file reference (run: flutter pub run build_runner build)
// import 'service_locator.config.dart';

final getIt = GetIt.instance;

@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: false,
)
Future<void> configureDependencies() async {
  await init();
}

// Manual setup until generated by injectable (or for reference)
Future<void> init() async {
  // External dependencies
  getIt.registerSingleton<FlutterSecureStorage>(
    const FlutterSecureStorage(),
  );

  // HTTP Client with security configuration
  getIt.registerSingleton<Dio>(_configureDio());

  // Repositories
  // getIt.registerSingleton<AuthRepository>(AuthRepositoryImpl(
  //   remoteDataSource: getIt(),
  //   localDataSource: getIt(),
  // ));

  // Use cases
  // getIt.registerSingleton<GetAuthUserUseCase>(
  //   GetAuthUserUseCase(authRepository: getIt()),
  // );
}

Dio _configureDio() {
  final dio = Dio(
    BaseOptions(
      baseUrl: 'https://api.example.com',  // Change to your API
      connectTimeout: const Duration(seconds: 30),
      receiveTimeout: const Duration(seconds: 30),
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
    ),
  );

  // Add logging interceptor (dev only)
  // dio.interceptors.add(LoggingInterceptor());

  // Add auth token interceptor
  dio.interceptors.add(
    InterceptorsWrapper(
      onRequest: (options, handler) async {
        // Add auth token if available
        final token = await getIt<FlutterSecureStorage>().read(key: 'auth_token');
        if (token != null) {
          options.headers['Authorization'] = 'Bearer $token';
        }
        return handler.next(options);
      },
      onError: (error, handler) async {
        // Handle 401 - refresh token or redirect to login
        if (error.response?.statusCode == 401) {
          // Implement token refresh or redirect to login
        }
        return handler.next(error);
      },
    ),
  );

  return dio;
}

// Environment-specific configuration
enum Environment { dev, staging, production }

Environment getEnvironment() {
  // Use --dart-define during build to set environment
  const env = String.fromEnvironment('ENV', defaultValue: 'dev');
  return Environment.values.byName(env);
}
